### ISSUE TITLE
Missing Kratos error IDs

### ISSUE THREAD

**Issue by nderjung** [ory/kratos-selfservice-ui-react-nextjs#10]
Hi,

Looks like Kratos is not yet providing error IDs, and so the cases are never caught by the axios error handler:

https://github.com/ory/kratos-react-nextjs-ui/blob/master/pkg/errors.tsx#L14-L51

This results in a blanket promise error which disrupts the authentication flow.

Can you advise when this will be available in Kratos? I can't find a relevant docs, PR or fork which introduces this functionality.  A search via Github finds [this](https://github.com/ory/kratos-selfservice-ui-node/blob/2ef520ccf0206b406b853dc1f709228cc83aba60/contrib/sdk/api.json#L2555) but doesn't provide any more implementation information.

Cheers!

**Comment by aeneasr** [comment]
Please wait for 0.7, it will work then!

**Comment by nderjung** [comment]
As in kratos v0.7? Isn't this already available?

When is the eta?

**Comment by aeneasr** [comment]
Release is scheduled for the Ory Summit: https://events.hubilo.com/ory-summit/register?mtm_campaign=ory-summit-2021&mtm_kwd=banner-landingpage

**Comment by nderjung** [comment]
Perfect, thanks!

**Comment by aeneasr** [comment]
you're welcome :)
