### ISSUE TITLE
Request; Being able to register a new account while being logged in

### ISSUE THREAD

**Issue by adharshmk96** [ory/kratos-selfservice-ui-react-nextjs#42]
Currently I can only reach the registration page If A session isn't there or not logged in.

I would like to be able to work with registration even when I'm logged in

When I reach the registration page after logging in, the SDK, I'm getting this error response when I'm into registration flow.
```
 {
    "error":{
       "id":"session_already_available",
       "code":400,
       "status":"Bad Request",
       "reason":"A valid session was detected and thus registration is not possible.",
       "message":"you are already logged in"
    }
 }
```

Example: Google allows us to sign up even though we are logged in.

**Comment by aeneasr** [comment]
You will need to log out first! Then you can sign up :)

**Comment by adharshmk96** [comment]
@aeneasr Yeah, I'm looking for a way to be able to sign up without logging out.

Basically I'm trying to have a system like google accounts where you can log in to a google account, and still register for a new one.
then, maybe login to another account too and have an account switcher

**Comment by aeneasr** [comment]
I see, that's unfortunately not currently possible - you can't register with an existing session :/
