### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'filter')

### ISSUE THREAD

**Issue by TorbenHammes** [ory/kratos-selfservice-ui-react-nextjs#45]
Hey there,
I get the following error if I want to use `/recovery` and `/verification`.
The flow component looks good, I think the error deals with the flow id I request automatically if I'm visiting the page without `?flow=<xyz>` but I don't have an idea to fix this issue.

Could you help me please :-D 

Thx
Torben

**Comment by aeneasr** [comment]
Can you please elaborate how you are setting up the project or even better have a reproducible example? Thanks!

**Comment by TorbenHammes** [comment]
Hey,
I installed your repo via git. At the beginning I got the following error: 
`It looks like you're trying to use TypeScript but do not have the required package(s) installed.`

Then I modified some dependencies in package.json to this:

```
"dependencies": {
    "@ory/client": "0.2.0-alpha.37",
    "@ory/integrations": "0.2.8",
    "@ory/themes": "~0.0.101",
    "classnames": "^2.3.1",
    "next": "v12.1.5-canary.7",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-toastify": "^8.0.3",
    "styled-components": "^5.3.1",
    "typescript": "^4.4.2"
  },
  "peerDependencies": {
    "next": "12.1.6",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "styled-components": "^5.3.1"
  },
  "devDependencies": {
    "@trivago/prettier-plugin-sort-imports": "^3.1.0",
    "@types/react": "^17.0.0",
    "@types/request": "^2.48.7",
    "@types/styled-components": "^5.1.13",
    "cypress": "^8.7.0",
    "eslint": "7.32.0",
    "eslint-config-next": "12.0.3",
    "ory-prettier-styles": "^1.1.2",
    "prettier": "^2.3.2",
    "rollup": "^2.56.3",
    "rollup-plugin-dts": "^4.0.0",
    "rollup-plugin-esbuild": "^4.5.0",
    "webpack-node-externals": "^3.0.0"
  }
```

Does this help?

**Comment by aeneasr** [comment]
Can you show the steps you used to end up with the error? Basically, all the steps that would help me do what you did to end up with the same error message. Did you follow as in the README stated the steps here: https://www.ory.sh/nextjs-authentication-spa-custom-flows-open-source ?

**Comment by TorbenHammes** [comment]
Does this help?
I started the frontend in development mode (yarn dev).
Then I opened the ui and this happens. 

https://user-images.githubusercontent.com/12980389/197511912-0c15e2e1-0396-4183-a949-37c907825270.mov

**Comment by aeneasr** [comment]
I tried reproducing this problem but could not:

```
git clone ...
npm i
npm run dev
```
