### ISSUE TITLE
Question: Will peer-dep be updated in the near future?

### ISSUE THREAD

**Issue by AdamNording** [ory/kratos-selfservice-ui-react-nextjs#60]
Hi! 
We are currently running a very old version of the kratos-selfservice-node-express and we want to move to the react-nextjs solution instead. 

But I was wondering if you have any plans to update:
* Next.js to latest
* React to latest
* Typescript to latest
* Styled-components to latest
?

Because NextJS 13 came with a lot of really nice features that we could have a lot of usage from.

**Comment by Benehiko** [comment]
Hi @AdamNording 

We will probably in the future, but it's not a high priority for us atm. This repository is used as an example and for end-to-end tests in Ory Kratos. 

The https://github.com/ory/kratos-selfservice-ui-node application is kept up to date and is used in production as the account experience in Ory Network.

**Comment by AdamNording** [comment]
Okey thank you for the update. 

Yeah I thought that that was the case. But we're gonna go with the React, NextJS so that we can use our internal components in the project.

Anyway, if you get the time to make the updates that would be appreciated. 

Thank you! @Benehiko

**Comment by AdamNording** [comment]
Got the answer I wanted :)
